Allow search on rich text macros
jpalmieri/best_search pull request #18
Opened 2017-07-14 21:13 UTC by PolRod

The API response for rich text macros is different from those with plain text. This allows the app to search for rich text macros as well.

2017-07-14 21:16 UTC, PolRod commented on app.js
> +        }.bind(this));
`{this.("I did this with this this because binding this this allows this function to have access to this.stripHTMLTags.")}.bind(this)`

2017-07-20 21:10 UTC, jpalmieri requested changes
Won't this make the string search behave differently for rich text comments? Anything inside html tags will be removed (e.g., link addresses), so it won't be matched against the query, but only if the comment is rich text, right? Maybe I'm mistaken.

In other words, it seems like a plain text comment with the same content as a rich text comment could return more results; in the case that the query matched something that was inside an html tag, the result would return for the plain text comment but not for the rich text one, right?

However, it does seem weird to be matching stuff inside html tags anyway. But maybe we should figure out a solution that creates the same (or at least similar) behavior for both comment types, ideally without removing functionality. What's the problem that's being addressed by removing the html tags from the rich text comments?

2017-07-20 21:10 UTC, jpalmieri commented on app.js
> +        return string.replace(/<br>/, " ").replace(/<(?:.|\n)*?>/gm, '');
so this replaces open `<br>` tags with spaces and then removes all other html tags?

2017-07-20 21:10 UTC, jpalmieri commented on app.js
> +        }.bind(this));
```javascript
this.("LGTM", function(yep) {
  return this.👍();
}.bind(this));
```

2017-07-20 22:48 UTC, PolRod commented on app.js
> +        return string.replace(/<br>/, " ").replace(/<(?:.|\n)*?>/gm, '');
Yeah, I thought it would make it more intuitive for searching things across lines.

2017-07-20 22:54 UTC, PolRod commented
The idea is that an agent that is looking for a sentence in a rich text macro will see "This is a **cool** macro" on the editor and should not need to know to search for `"This is a <strong>cool</strong> macro"`. If we did not strip the tags, no results would come back for "this is a cool macro".

On the other hand, if there are tags on a plain text macro, they will show on the plain text editor, and the agent will expect them to show up if making a search.

In other words, I'm trying to make the results be the closest to what an agent would expect by looking at the macro.

2017-07-21 08:33 UTC, jpalmieri commented
That totally makes sense. Thanks for clarifying! 🥇 💯

2017-07-21 08:33 UTC, jpalmieri approved these changes

2017-07-21 08:34 UTC, jpalmieri commented
@PolRod I'm pretty sure you have merge permissions, so I'll let you merge whenever you want. But lmk if you can't. ✌️

2017-07-21 08:34 UTC, jpalmieri commented
also, thanks for the contribution! 🙏

2017-07-21 21:57 UTC, merged

2017-07-22 22:56 UTC, jpalmieri commented
forgot something. My bad

![image](https://media.giphy.com/media/a8AXSGtbEl1du/giphy.gif)